In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [8]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
import numpy as np
zero_arr=np.zeros(5)
print(zero_arr)

[0. 0. 0. 0. 0.]


In [11]:
import numpy as np
zero_arr=np.zeros((5,2))
print(zero_arr)
print("Datatype of the array:",zero_arr.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Datatype of the array: float64


In [14]:
import sys
s=range(1000)
print("Size of each element of list in bytes:",sys.getsizeof(s))
print("Size of the whole list in bytes:",sys.getsizeof(s)*len(s))

Size of each element of list in bytes: 48
Size of the whole list in bytes: 48000


In [17]:
D=np.arange(1000)
print("Sie of each element of the Numpy array in bytes:",D.itemsize)
print("Size of the whole Numpy array in bytes:",D.size*D.itemsize)

Sie of each element of the Numpy array in bytes: 4
Size of the whole Numpy array in bytes: 4000


In [19]:
ones_arr=np.ones(4)
print(ones_arr)

[1. 1. 1. 1.]


In [21]:
ones_arr=np.ones((6,5))
print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
empty_arr=np.empty((3,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
identity_matrix=np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [24]:
arr1=np.array([1,2,3],dtype=np.float64)
print(arr1.dtype)

float64


In [27]:
arr=np.array([1,2,3])
print("Before converting:",arr,arr.dtype)
new_arr=arr.astype('f')
print("After converting:",new_arr,arr.dtype)

Before converting: [1 2 3] int32
After converting: [1. 2. 3.] int32


In [28]:
new_arr=arr.astype('f')
print("After converting:",new_arr,arr.dtype)

After converting: [1. 2. 3.] int32


In [30]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print("array1\n",arr1,arr1.dtype)
print("array2\n",arr2,arr2.dtype)

array1
 [0 1 2 3 4 5 6 7 8 9] int32
array2
 [-0.65073224  0.27094462  0.52384714  0.2595481  -1.73703108 -0.47149152
  0.00333794 -0.11348238  0.60900587 -0.52470941] float64


In [31]:
new_arr=arr2.astype('f')
print(new_arr)

[-0.6507322   0.27094463  0.52384716  0.2595481  -1.7370311  -0.47149152
  0.00333794 -0.11348238  0.60900587 -0.5247094 ]


In [32]:
new_arr=arr1.astype(arr2.dtype)
print(new_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [34]:
new_arr=arr1.astype('c')
print(new_arr)

[b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9']


In [35]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)

[ 6  8 10 12]


In [36]:
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a^b)

[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1 2 3 4]
[ 4  4  4 12]


In [38]:
arr=np.arange(12)
newarr=arr.reshape(4,3)
print(newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
new_arr=arr.reshape((4,3),order='F')
print(new_arr)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [42]:
arr=np.array([[1,2,3,4,5,8],[6,7,8,9,9,4]])
print(arr)
newarr=arr.reshape(3,2,2)
print(newarr)
newarr1=newarr.reshape(3,-1)
print(newarr1)

[[1 2 3 4 5 8]
 [6 7 8 9 9 4]]
[[[1 2]
  [3 4]]

 [[5 8]
  [6 7]]

 [[8 9]
  [9 4]]]
[[1 2 3 4]
 [5 8 6 7]
 [8 9 9 4]]


In [43]:
org_arr=np.array([[10,2],[30,40]])
flatten_arr=org_arr.flatten()
print("Original array:",org_arr)
print("Flatten array:",flatten_arr)

Original array: [[10  2]
 [30 40]]
Flatten array: [10  2 30 40]


In [45]:
ravel_arr=org_arr.ravel()
print("Raveled array:",ravel_arr)

Raveled array: [10  2 30 40]


In [46]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[2,1],[4,5]])
great_than=arr1>arr2
less_than=arr1<arr2
equal_to=arr1==arr2
print(great_than)
print(less_than)
print(equal_to)

[[False  True]
 [False False]]
[[ True False]
 [ True  True]]
[[False False]
 [False False]]


In [47]:
x=np.arange(10)
print("x=",x)

x= [0 1 2 3 4 5 6 7 8 9]


In [49]:
print(x[:5])
print(x[5:])
print(x[::2])
print(x[4:7])

[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[4 5 6]
