In [9]:
import pandas as pd
data=[10,20,30,40,50]
series=pd.Series(data)
series

0     10
1     20
2     30
3     40
4     50
5    abd
dtype: object

In [2]:
series.dtype

dtype('int64')

In [4]:
series.values

array([10, 20, 30, 40, 50], dtype=int64)

In [5]:
series.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
print(series.values)

[10 20 30 40 50]


In [7]:
print(series.name)

None


In [11]:
series.name="values"
series

0     10
1     20
2     30
3     40
4     50
5    abd
Name: values, dtype: object

In [13]:
series[0]

10

In [15]:
a=[1,7,9]
myvar=pd.Series(a,index=['x','y','z'])
myvar

x    1
y    7
z    9
dtype: int64

In [28]:
import pandas as pd
data=[10,20,30,40,50]
s=pd.Series(data)
s


0    10
1    20
2    30
3    40
4    50
dtype: int64

In [29]:
gt=s>25
print(gt)

0    False
1    False
2     True
3     True
4     True
dtype: bool


In [30]:
series_ft=s[s>25]
print(series_ft)

2    30
3    40
4    50
dtype: int64


In [32]:
import numpy as np
s_sqrt=np.sqrt(series)
print(s_sqrt)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [33]:
s=s+100
print(s)

0    110
1    120
2    130
3    140
4    150
dtype: int64


In [36]:
data=['a','b','c']
d=pd.Series(data)
print(d)


0    a
1    b
2    c
dtype: object


In [38]:
print(d.dtype)

object


In [39]:
data={
    "calories": [343,890,607],
    "Duration": [43,89,67]
}
df=pd.DataFrame(data)
df

calories  Duration
0       343        43
1       890        89
2       607        67

In [41]:
data={'state':['Delhi','Delhi','Delhi','Goa','Goa','Goa'],
     'Year':[2000,2001,2002,2003,2004,2005],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
print(frame)

   state  Year  pop
0  Delhi  2000  1.5
1  Delhi  2001  1.7
2  Delhi  2002  3.6
3    Goa  2003  2.4
4    Goa  2004  2.9
5    Goa  2005  3.2


In [42]:
frame=pd.DataFrame(data,columns=['Year','state','pop'])
print(frame)

   Year  state  pop
0  2000  Delhi  1.5
1  2001  Delhi  1.7
2  2002  Delhi  3.6
3  2003    Goa  2.4
4  2004    Goa  2.9
5  2005    Goa  3.2


In [44]:
frame2 = pd.DataFrame(data, columns=['Year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)

       Year  state  pop debt
one    2000  Delhi  1.5  NaN
two    2001  Delhi  1.7  NaN
three  2002  Delhi  3.6  NaN
four   2003    Goa  2.4  NaN
five   2004    Goa  2.9  NaN
six    2005    Goa  3.2  NaN


In [45]:
print(frame['pop'])

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64


In [46]:
print(frame['state'])

0    Delhi
1    Delhi
2    Delhi
3      Goa
4      Goa
5      Goa
Name: state, dtype: object


In [47]:
print(frame['Year'])

0    2000
1    2001
2    2002
3    2003
4    2004
5    2005
Name: Year, dtype: int64


In [49]:
print(frame2.loc['one'])

Year      2000
state    Delhi
pop        1.5
debt       NaN
Name: one, dtype: object


In [50]:
print(frame2.loc[['two','three']])

       Year  state  pop debt
two    2001  Delhi  1.7  NaN
three  2002  Delhi  3.6  NaN


In [51]:
frame2['debt'] = 12.4
print(frame2)

       Year  state  pop  debt
one    2000  Delhi  1.5  12.4
two    2001  Delhi  1.7  12.4
three  2002  Delhi  3.6  12.4
four   2003    Goa  2.4  12.4
five   2004    Goa  2.9  12.4
six    2005    Goa  3.2  12.4


In [52]:
frame2['debt'] = np.arange(6.)
print(frame2)

       Year  state  pop  debt
one    2000  Delhi  1.5   0.0
two    2001  Delhi  1.7   1.0
three  2002  Delhi  3.6   2.0
four   2003    Goa  2.4   3.0
five   2004    Goa  2.9   4.0
six    2005    Goa  3.2   5.0


In [53]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
print(frame2)

       Year  state  pop  debt
one    2000  Delhi  1.5   NaN
two    2001  Delhi  1.7  -1.2
three  2002  Delhi  3.6   NaN
four   2003    Goa  2.4  -1.5
five   2004    Goa  2.9  -1.7
six    2005    Goa  3.2   NaN


In [54]:
frame2['eastern'] = frame2.state == 'Ohio'
print(frame2)

       Year  state  pop  debt  eastern
one    2000  Delhi  1.5   NaN    False
two    2001  Delhi  1.7  -1.2    False
three  2002  Delhi  3.6   NaN    False
four   2003    Goa  2.4  -1.5    False
five   2004    Goa  2.9  -1.7    False
six    2005    Goa  3.2   NaN    False


In [55]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [58]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
obj4 = obj3.reindex(range(6), method='ffill') #forward-fills the values
obj4

0      blue
2    purple
4    yellow
dtype: object


0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [57]:
obj5 = obj3.reindex(range(6), method='bfill')
print("\nMethod 'bfill':")
print(obj5)


Method 'bfill':
0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object


In [59]:
obj7 = pd.Series([1, 2, 3], index=[0, 2, 5])
obj8 = obj7.reindex(range(7), method='ffill', limit=1)
print("\nLimit:")
print(obj8)


Limit:
0    1.0
1    1.0
2    2.0
3    2.0
4    NaN
5    3.0
6    3.0
dtype: float64


In [60]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
print(new_obj)
obj.drop(['d', 'c'])

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64


a    0.0
b    1.0
e    4.0
dtype: float64

In [62]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Dallas', 'NJ', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [63]:
data.drop(['NJ', 'Ohio'])

one  two  three  four
Dallas      4    5      6     7
New York   12   13     14    15

In [65]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
print("obj['b']= \n",obj['b'])

obj['b']= 
 1.0


In [66]:
print("obj[1]= \n",obj[1])

obj[1]= 
 1.0


In [67]:
print("obj[2:4]= \n",obj[2:4])

obj[2:4]= 
 c    2.0
d    3.0
dtype: float64


In [68]:
print("obj[['b', 'a', 'd']]= \n",obj[['b', 'a', 'd']])

obj[['b', 'a', 'd']]= 
 b    1.0
a    0.0
d    3.0
dtype: float64


In [69]:
print("obj[b:d]= \n",obj['b':'d'])

obj[b:d]= 
 b    1.0
c    2.0
d    3.0
dtype: float64


In [70]:
print("obj[obj < 2]= \n",obj[obj < 2])

obj[obj < 2]= 
 a    0.0
b    1.0
dtype: float64


In [71]:
data[1:5]

one  two  three  four
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [72]:
data.loc['Dallas', ['two', 'three']]

two      5
three    6
Name: Dallas, dtype: int32

In [73]:
data.at['Dallas', 'one']

4

In [74]:
data.iloc[3]

one      12
two      13
three    14
four     15
Name: New York, dtype: int32

In [75]:
data.iloc[2:5, 0:2]

one  two
NJ          8    9
New York   12   13

In [76]:
data.iloc[1:4, :]

one  two  three  four
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [77]:
print(data.three > 5)
data[data.three > 5]

Ohio        False
Dallas       True
NJ           True
New York     True
Name: three, dtype: bool


one  two  three  four
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [78]:
data<5
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Dallas      0    5      6     7
NJ          8    9     10    11
New York   12   13     14    15